name = "dropbeats-webhook-proxy"
main = "src/worker.ts"
compatibility_date = "2024-01-18"

[vars]
SUPABASE_URL = "https://trtxfdsssreqhuajpvqk.supabase.co"

[observability.logs]
enabled = true

[dev]
port = 8787
local_protocol = "http"
[triggers]
crons = [ ] 